📘 PART 1: NumPy – Numerical Python
NumPy is used for:

Fast array operations

Working with vectors, matrices, and tensors

Mathematical & statistical functions

In [2]:
import numpy as np
arr1=np.array([1,2,3])
print("1D array:",arr1)

1D array: [1 2 3]


In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
#Step 1.2: Array Properties
print("Shape",arr2.shape)
print("Size",arr2.size)
print("datatype",arr2.dtype)

Shape (2, 3)
Size 6
datatype int64


In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Dot Product:", np.dot(a, b))


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot Product: 32


In [6]:
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((2, 2)))
print("Random numbers:\n", np.random.rand(3))
print("Range:\n", np.arange(0, 10, 2))  # 0 to 8, step 2


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]]
Random numbers:
 [0.6437648  0.62324009 0.48840367]
Range:
 [0 2 4 6 8]


In [8]:
arr3 = np.array([[1,2,3],[4,5,6],[4,7,8]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [4 7 8]]


In [9]:
print(arr3[1])

[4 5 6]


In [11]:
print("Value at [1,2]:", arr3[1,2])

Value at [1,2]: 6


In [13]:
#Array reshaping
a = np.arange(6)
a= a.reshape((2,3))
print(a)

[[0 1 2]
 [3 4 5]]


In [15]:
#Broadcasting
a=np.array([1,2,3])
b=2
print(b+a)

[3 4 5]


In [16]:
#3 Aggregation Functions\
arr = np.array([[1,2,3],[4,5,6]])
print(arr.sum()) #total sum
print(arr.sum(axis=0)) #column wise sum
print(arr.sum(axis=1)) #row wise sum
print(arr.min())
print(arr.max())
print(arr.mean())
print(np.median(arr))
print(np.std(arr))

21
[5 7 9]
[ 6 15]
1
6
3.5
3.5
1.707825127659933


In [18]:
#Boolean Indexing (Very Powerful)
arr = np.array([10, 20, 30, 40])
print(arr[arr > 25])  # [30 40]


[30 40]


When learning a new function, always do:
help(function_name)
help(np.sum)
sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, ...)


Help on _ArrayFunctionDispatcher in module numpy:

median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
    Compute the median along the specified axis.
    
    Returns the median of the array elements.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : {int, sequence of int, None}, optional
        Axis or axes along which the medians are computed. The default,
        axis=None, will compute the median along a flattened version of
        the array.
        
        .. versionadded:: 1.9.0
    
        If a sequence of axes, the array is first flattened along the
        given axes, then the median is computed along the resulting
        flattened axis.
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
        but the type (of the output) will be cast if necessary.
    ov